### ISSUE TITLE
Bug: Are nested views supported? 

### ISSUE THREAD

**Issue by jderr-mx** [kenjis/ci3-to-4-upgrade-helper#17]
**Describe the bug**
I am working on migrating an application that has many nested views
If in one view I include another with `$this->load->view('view_name');`

Stack trace:
```
Call to a member function view() on null
#0 /var/www/occrra/vendor/codeigniter4/framework/system/View/View.php(213): include()
#1 /var/www/occrra/vendor/codeigniter4/framework/system/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#2 /var/www/occrra/vendor/kenjis/ci3-to-4-upgrade-helper/src/CI3Compatible/Core/CI_Loader.php(116): CodeIgniter\View\View->render('inc/header', NULL, true)
#3 /var/www/occrra/vendor/kenjis/ci3-to-4-upgrade-helper/src/CI3Compatible/Core/CI_Loader.php(105): Kenjis\CI3Compatible\Core\CI_Loader->viewRender('inc/header', Array)
#4 /var/www/occrra/app/Controllers/User.php(505): Kenjis\CI3Compatible\Core\CI_Loader->view('inc/header', Array)
```

I also tried this with a new CI4 instance 

where I updated the Home controller with:
```
use Kenjis\CI3Compatible\Core\CI_Controller;

class Home extends CI_Controller
```

Then I created a view called `test_view.php` and loaded it in the `welcome_view`

`<?php $this->load->view('test_view'); ?>`

It creates this stack trace
```
CRITICAL - 2023-03-08 02:24:06 --> Undefined property: CodeIgniter\View\View::$load
in APPPATH/Views/welcome_message.php on line 323.
 1 APPPATH/Views/welcome_message.php(323): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: CodeIgniter\\View\\View::$load', 'APPPATH/Views/welcome_message.php', 323)
 2 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/welcome_message.php')
 3 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 VENDORPATH/kenjis/ci3-to-4-upgrade-helper/src/CI3Compatible/Core/CI_Loader.php(116): CodeIgniter\View\View->render('welcome_message', null, true)
 5 VENDORPATH/kenjis/ci3-to-4-upgrade-helper/src/CI3Compatible/Core/CI_Loader.php(105): Kenjis\CI3Compatible\Core\CI_Loader->viewRender('welcome_message', [])
 6 APPPATH/Controllers/Home.php(9): Kenjis\CI3Compatible\Core\CI_Loader->view('welcome_message', [])
 7 SYSTEMPATH/CodeIgniter.php(934): App\Controllers\Home->index()
 8 SYSTEMPATH/CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH/CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH/Commands/Server/rewrite.php(47): require_once('FCPATH/index.php')
```

**ci3-to-4-migration-helper version**
Which version (and branch, if applicable) the bug is in.

**Expected behavior, and steps to reproduce if appropriate**
A clear and concise description of what you expected to happen,
and how you got there.  
Feel free to include a text/log extract, but use a pastebin facility for any
screenshots you deem necessary.

**Context**
 - OS: [e.g. Windows 99]
 - Web server [e.g. Apache 1.2.3]
 - PHP version [e.g. 6.5.4]

**Comment by kenjis** [comment]
Try v0.6.1 or later.

**Comment by kenjis** [comment]
See #23
